import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const REAL_PLACES = [
  {
    name: "Central Park",
    description: "Free iconic urban park with lakes, walking paths, free concerts in summer, perfect for picnics, jogging, and making friends at Sheep Meadow. Bike rentals available!",
    category: "park",
    address: "New York, NY 10024",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.785091,
    lng: -73.968285,
    cover_image_url: "https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Bryant Park",
    description: "Free! Play ping pong in summer, free WiFi, outdoor movies, yoga classes, chess tables, winter ice skating. Great for meeting people and studying outdoors.",
    category: "park",
    address: "New York, NY 10018",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.753597,
    lng: -73.983233,
    cover_image_url: "https://images.unsplash.com/photo-1615835360439-2e8e7c28e69f?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Stavros Niarchos Foundation Library",
    description: "Free! Beautiful modern library with study spaces, exhibitions, free events, amazing reading room. Perfect for studying, free WiFi, meeting creative people.",
    category: "library",
    address: "476 5th Ave, New York, NY 10018",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.753182,
    lng: -73.983948,
    cover_image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Brooklyn Bridge Park",
    description: "Free waterfront park! Stunning Manhattan views, free kayaking in summer, beach volleyball, picnic spots, sunset photos. Meet locals and tourists.",
    category: "park",
    address: "Brooklyn, NY 11201",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.701736,
    lng: -73.996864,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "The High Line",
    description: "Free elevated park! Walk above the streets, art installations, food vendors, gardens, amazing photo spots. Meet creative people and enjoy unique NYC views.",
    category: "park",
    address: "New York, NY 10011",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.747993,
    lng: -74.004764,
    cover_image_url: "https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "The Metropolitan Museum of Art",
    description: "Pay what you wish for NY residents! World-class art collection, rooftop garden with city views, free events. Perfect for culture lovers and Instagram photos.",
    category: "museum",
    address: "1000 5th Ave, New York, NY 10028",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.779437,
    lng: -73.963244,
    cover_image_url: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "MoMA (Museum of Modern Art)",
    description: "Free admission Fridays 4-8pm! See Van Gogh, Picasso, contemporary art, design exhibitions. Great date spot and conversation starter with art lovers.",
    category: "museum",
    address: "11 W 53rd St, New York, NY 10019",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.761433,
    lng: -73.977622,
    cover_image_url: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Brooklyn Public Library - Central Branch",
    description: "Free! Grand reading room, study spaces, community events, exhibitions, job resources. Meet students, freelancers, and locals. Free WiFi!",
    category: "library",
    address: "10 Grand Army Plaza, Brooklyn, NY 11238",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.672404,
    lng: -73.968582,
    cover_image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Washington Square Park",
    description: "Free! Chess tables, street performers, live music, fountain, dog park. Hub for NYU students, artists, musicians. Great vibes and easy to make friends.",
    category: "park",
    address: "New York, NY 10012",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.730823,
    lng: -73.997332,
    cover_image_url: "https://images.unsplash.com/photo-1563841930606-67e2bce48b78?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Domino Park",
    description: "Hidden gem! Waterfront park in Williamsburg with elevated walkway, food vendors, play areas, amazing skyline views. Chill Brooklyn crowd, weekend markets.",
    category: "park",
    address: "Brooklyn, NY 11249",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.715419,
    lng: -73.963569,
    cover_image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "The Cloisters",
    description: "Hidden museum! Pay what you wish for NY residents. Medieval art in a castle setting, gardens, peaceful views. Perfect escape from city crowds, unique photos.",
    category: "museum",
    address: "99 Margaret Corbin Dr, New York, NY 10040",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.864950,
    lng: -73.931806,
    cover_image_url: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Chelsea Market",
    description: "Free to explore! Food hall with artisan shops, restaurants, bakeries. Sample foods, meet foodies, rainy day hangout spot, Instagram-worthy.",
    category: "mall",
    address: "75 9th Ave, New York, NY 10011",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.742450,
    lng: -74.006080,
    cover_image_url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Gantry Plaza State Park",
    description: "Hidden spot! Queens waterfront with panoramic Manhattan views, piers, playgrounds. Great for sunset photos, quiet reading, less crowded than Manhattan parks.",
    category: "park",
    address: "Queens, NY 11101",
    city: "Queens",
    region: "New York",
    country: "United States",
    lat: 40.745255,
    lng: -73.958196,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "New York Public Library - Stephen A. Schwarzman Building",
    description: "Free! Iconic building with grand reading rooms, exhibitions, free tours. Perfect study spot, meet scholars and tourists, architectural photography.",
    category: "library",
    address: "476 5th Ave, New York, NY 10018",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.753182,
    lng: -73.982253,
    cover_image_url: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Smorgasburg Williamsburg",
    description: "Free entry! Outdoor food market every weekend, 100+ vendors, try food from $5-15. Meet foodies, live music, great for groups and dates. Seasonal.",
    category: "other",
    address: "90 Kent Ave, Brooklyn, NY 11249",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.721267,
    lng: -73.963375,
    cover_image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Roosevelt Island",
    description: "Free tram ride with MetroCard! Peaceful island with waterfront walks, lighthouse, parks, skyline views. Hidden gem for escaping crowds and picnics.",
    category: "landmark",
    address: "Roosevelt Island, NY 10044",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.759020,
    lng: -73.950620,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Governors Island",
    description: "Free ferry! Car-free island with art installations, hammocks, hills with views, bike rentals, food vendors. Summer weekends only. Great for groups and exploring.",
    category: "landmark",
    address: "New York, NY 10004",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.689249,
    lng: -74.016632,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Brooklyn Botanic Garden",
    description: "Free on weekday mornings! Cherry blossoms in spring, Japanese garden, rose garden, greenhouse. Peaceful walks, photography, meet nature lovers and couples.",
    category: "park",
    address: "990 Washington Ave, Brooklyn, NY 11225",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.668399,
    lng: -73.963784,
    cover_image_url: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Staten Island Ferry",
    description: "Always free! 25-minute ride with Statue of Liberty and skyline views. Open 24/7, indoor and outdoor decks. Best free tourist activity, sunset rides are stunning!",
    category: "landmark",
    address: "New York, NY 10004",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.701671,
    lng: -74.013169,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Union Square",
    description: "Free! Farmers market Mon/Wed/Fri/Sat, chess tables, street performers, protests and rallies. Hub for activists, students, vendors. Easy to strike up conversations.",
    category: "park",
    address: "New York, NY 10003",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.735832,
    lng: -73.991065,
    cover_image_url: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Fort Tryon Park",
    description: "Hidden gem! Uptown park with cliffside views, gardens, trails, home to The Cloisters. Peaceful, less crowded, perfect for long walks and nature photography.",
    category: "park",
    address: "New York, NY 10040",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.859722,
    lng: -73.931389,
    cover_image_url: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Socrates Sculpture Park",
    description: "Free hidden gem in Queens! Outdoor art museum with rotating sculptures, waterfront views, yoga classes, movie nights. Meet artists and local Queens community.",
    category: "park",
    address: "32-01 Vernon Blvd, Queens, NY 11106",
    city: "Queens",
    region: "New York",
    country: "United States",
    lat: 40.768056,
    lng: -73.939444,
    cover_image_url: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "The American Museum of Natural History",
    description: "Pay what you wish for NY residents! Dinosaurs, space exhibits, planetarium shows, cultural halls. Educational and fun, great for all ages, iconic NYC experience.",
    category: "museum",
    address: "200 Central Park West, New York, NY 10024",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.781324,
    lng: -73.973988,
    cover_image_url: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "The Morgan Library & Museum",
    description: "Free Fridays 5-7pm! Historic library with rare books, manuscripts, art exhibitions, beautiful architecture. Hidden gem for book lovers and history buffs.",
    category: "library",
    address: "225 Madison Ave, New York, NY 10016",
    city: "New York",
    region: "New York",
    country: "United States",
    lat: 40.749167,
    lng: -73.981667,
    cover_image_url: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
  {
    name: "Prospect Park",
    description: "Free! Brooklyn's Central Park with meadows, lake, zoo, concerts, farmer's market, sports fields. Less touristy, locals hang out, great for sports and picnics.",
    category: "park",
    address: "Brooklyn, NY 11225",
    city: "Brooklyn",
    region: "New York",
    country: "United States",
    lat: 40.660204,
    lng: -73.968857,
    cover_image_url: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800",
    is_verified: true,
    post_count: 0,
    follower_count: 0,
  },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Check existing places
    const existing = await base44.asServiceRole.entities.Place.list("-created_date", 100);
    const existingNames = new Set(existing.map(p => p.name));

    const created = [];
    for (const place of REAL_PLACES) {
      if (!existingNames.has(place.name)) {
        const newPlace = await base44.asServiceRole.entities.Place.create(place);
        created.push(newPlace.name);
      }
    }

    return Response.json({
      success: true,
      message: `Seeded ${created.length} new places`,
      created,
      skipped: REAL_PLACES.length - created.length,
    });
  } catch (error) {
    console.error("Seed error:", error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});